"""gen_art.py — emit src/content/art.ts: a static require() map of card art.

Metro cannot require() images with a dynamic path, so we generate an explicit
module mapping each approved card id to its bundled asset. Cards without
approved art are omitted; the UI renders the branded placeholder back.
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BUNDLE = REPO / "src" / "content" / "deck-bundle.json"
OUT = REPO / "src" / "content" / "art.ts"

d = json.loads(BUNDLE.read_text(encoding="utf-8"))
lines = [
    "// Generated by scripts/gen_art.py — do not edit by hand.",
    "// Maps card id -> bundled image via static require() (Metro-safe).",
    "export const cardArt: Record<string, number> = {",
]
for c in d["cards"]:
    a = c["artwork"]
    if a["status"] == "approved" and a.get("assetKey"):
        lines.append(f'  {json.dumps(c["id"])}: require("../../assets/cards/{a["assetKey"]}"),')
lines.append("};")
lines.append("")
lines.append("export function hasArt(cardId: string): boolean {")
lines.append("  return Object.prototype.hasOwnProperty.call(cardArt, cardId);")
lines.append("}")
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT} with {sum(1 for c in d['cards'] if c['artwork']['status']=='approved')} entries")
